### PR TITLE
Enable Catalan for HEDA

### PR DESCRIPTION
**Pull request by xinnanlisf**
# Critical Changes

# Changes
- We're excited to announce that we've added support for Catalan as a platform-only language. Support of platform-only languages is more limited than fully supported languages and end-user languages. Also keep in mind that labels and custom labels that were not translated with this release will be translated in a future release.

- Before using any HEDA translations, first enable Translation Workbench from Setup, in Translation Settings (for details, see [Enable and Disable the Translation Workbench](https://help.salesforce.com/articleView?id=customize_wbench.htm&type=5)). Then, to enable Catalan for HEDA, from Setup, in Language Settings, select **Enable platform-only languages**, move Catalan to the Displayed Languages list, and click **Save**. You can then change the language for your org or have users change their personal language settings. 

# Issues Closed

# New Metadata
Account-ca.objectTranslation
Address__c-ca.objectTranslation
Affiliation__c-ca.objectTranslation
Affl_Mappings__c-ca.objectTranslation
Contact-ca.objectTranslation
Course_Enrollment__c-ca.objectTranslation
Course_Offering__c-ca.objectTranslation
Course__c-ca.objectTranslation
Error__c-ca.objectTranslation
Hierarchy_Settings__c-ca.objectTranslation
Program_Enrollment__c-ca.objectTranslation
Relationship_Auto_Create__c-ca.objectTranslation
Relationship_Lookup__c-ca.objectTranslation
Relationship__c-ca.objectTranslation
Term__c-ca.objectTranslation
Trigger_Handler__c-ca.objectTranslation
ca.translation

# Deleted Metadata

# Testing Notes

1. Go to Setup -> Language Settings, click "Enable platform-only languages", then move Catalan over to "Displayed Languages" and Save
2. Click your profile image, then "Settings"
3. Select Language & Time Zone in the left menu
4. Update language to "Catala"

### CODE REVIEW

**Comment by lparrott** [comment]
@juliesnow I'm not sure what notes this needs, I suppose it should be similar to the French translations.
@annejackson This PR is ready to test.

**Comment by juliesnow** [comment]
@lparrott @annejackson @lianeyee 
Thanks, Luke. Liane and I will finalize this in about half an hour when we meet.

**Comment by juliesnow** [comment]
@xinnanlisf @lparrott Hi both. Can you please provide us with the steps users need to complete to enable Catalan in HEDA? How is the process to enable different than for French? Thanks!

**Comment by juliesnow** [comment]
Nevermind...looking at testing notes now. Sorry!

**Comment by xinnanlisf** [comment]
@juliesnow 

Looks good to me!

**Comment by xinnanlisf** [comment]
Thanks @pedrodalcol for fixing the conflicts. 

@annejackson the PR looks good but could you do a quick double check and make sure the translation is still working? Maybe just a spin up a scratch org and ensure a user can select catalan as his/her language.

**Comment by annejackson** [comment]
I will do that @xinnanlisf - will be testing it Monday!

**Comment by annejackson** [comment]
@xinnanlisf 
Testing is complete. However, we are not going to merge it into this release in case we have any issues merging into the release with devs away for TrailheadX. So far, did the following:
1. Tested with language set to English, did high level feature checks. Saw English.
2. Tested with language set to Catalan, did high level feature checks. Saw most things in Catalan.
I did notice there is a good amount of things that aren't translated. Like the Heda Settings page was all in English, and also some of the HEDA dialogs. 

Not sure if there are any tickets open in the HEDA product tag for items missing Catalan translations or not.  @ceiroa @dylanhansen

**Comment by juliesnow** [comment]
I'm fine w/ that. Leave the details in bullet 1 and replace second bullet w/ "Some labels and custom labels, including some in HEDA Settings, that didn't make it into this round of translation will be translated in a future release." Okay?

**Comment by kbangsberg** [comment]
@juliesnow - your suggestions sound great. Thanks!

**Comment by juliesnow** [comment]
@xinnanlisf @lianeyee Have updated the comments w/ requirement to enable Translation Workbench. Pls approve/modify.

**Comment by xinnanlisf** [comment]
@juliesnow 

Looks good to me!

**Comment by lianeyee** [comment]
@juliesnow Added the link to the Translation Workbench help topic and reformatted a few UI items.

**Comment by annejackson** [comment]
I am still not seeing Heda Settings in Catalan..will work with @xinnanlisf more on this. Also have to do some spot checking regressions with the new fix from Xinnan.

**Comment by annejackson** [comment]
I finished my tests for Catalan in a non namespaced scrach org. Heda settings page is working and is translated. I also did a high level regression check which passed. Merging pull request. fyi @xinnanlisf

**Comment by juliesnow** [comment]
@ceiroa @xinnanlisf @lianeyee Pls verify updated Comment section. TIA!!

**Comment by ceiroa** [comment]
Looks good to me, @juliesnow! Hopefully the format will persist after RelEng regenerates the notes.

**Comment by lianeyee** [comment]
@juliesnow I made a couple of small edits. 1) Added for emphasis the point about "Catalan or another language" and 2) Broke out the second point in its own bullet and clarified that the instructions are specific to platform-only languages.

**Pull request merged**
