### PR TITLE
Prevent User Managed Trigger handlers from being deleted.

### LINKED ISSUE #424: TDTM not respecting "User Managed" field on trigger handlers
User Jim Hubert in the Power of Us Hub alerted us to this issue here: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000DA0Q&fId=0D58000003LKN3Z&fromEmail=1

### PR DESCRIPTION
**Pull request by davidjray**
# Critical Changes

# Changes
- Trigger Handler records marked as User Managed are no longer deleted when upgrading from HEDA release 1.32 to later versions

# Issues Closed
Fixes #424

### CODE REVIEW

**Comment by davidjray** [comment]
@lianeyee Do you mind double checking my release notes?

**Comment by lianeyee** [comment]
@davidjray If it's OK to not mention the post-install script (do customers care about our internal scripts?), I recommend changing from "- Prevent deletion of Trigger Handler records when they're marked as "User Managed" to what I put in Changes above.

**Comment by davidjray** [comment]
@lianeyee I think you are right about not mentioning the install script, but maybe we should say something about "On Upgrade" since that is when this was happening?

Feel free to edit the changes at your leisure.

**Comment by lianeyee** [comment]
@davidjray Yes, good point! Is this only upon upgrade to 1.33 or will this happen with every subsequent release?

**Comment by davidjray** [comment]
@lianeyee It was 1.33 and would have been 1.34 if we didn't cancel the release. We were notified of the issue due to the push to sandboxes of 1.34, so maybe we mention 1.34 that as well?

**Comment by lianeyee** [comment]
@davidjray "when upgrading from HEDA release 1.32 to later versions"?

**Comment by davidjray** [comment]
Perfect @lianeyee

**Comment by lianeyee** [comment]
As always, a pleasure doing business with you, @davidjray

**Comment by ceiroa** [comment]
@davidjray The code looks great, but I have 2 operational questions:

1. Is there a matching WI in AA to link it to? If not, should this item be imported into AA?

2. How would you recommend @chrismcmahon and I to manually test this item?

Thank you!

**Comment by davidjray** [comment]
**lurch: attach W-018668

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PFf5AAG" target="_blank">W-018668</a>

**Comment by davidjray** [comment]
@ceiroa and @chrismcmahon to test you would simply run the install script method for updating TDTM config directly:
```
List<TDTM_Global_API.TdtmToken> defaultTdtmConfig = TDTM_Global_API.getDefaultTdtmConfig(); // Get the new defaults
STG_InstallScript.updateDefaultTdtmConfig(defaultTdtmConfig); // Process defaults
```
If testing against managed code, of course you'd prepend the namespace to the classes.

**Pull request merged**
