### PR TITLE
Update package.xml

### PR DESCRIPTION
**Pull request by davidjray**
# Critical Changes

# Changes
Update package.xml format

# Issues Closed

### CODE REVIEW

**Comment by davidjray** [comment]
I confirmed these changes with @jlantz, the previous format was actually incorrect. 

From Jason "The removal of Account and Contact is correct as the package doesn't contain those CustomObjects, only their CustomFields, WebLinks, etc."

FYI @ceiroa @paulmalenke

**Comment by ceiroa** [comment]
Hmm, I don't think that's correct. The package includes these objects, in order to be able to include our custom fields:
https://github.com/SalesforceFoundation/HEDAP/blob/master/src/objects/Account.object
https://github.com/SalesforceFoundation/HEDAP/blob/master/src/objects/Contact.object

Also, with this change CustomLabels is listed twice.

**Comment by davidjray** [comment]
Take a look at the NPSP [package.xml](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/package.xml#L1506-L1509), it contains the same nodes.

**Comment by ceiroa** [comment]
I'm pretty sure the CustomLabels thing is a bug in CumulusCI. I've told that to @jlantz for couple of years.

The objects thing might be correct. I have to think about it a little more. In any case, I don't think having them listed is causing any harm.

**Comment by davidjray** [comment]
I agree, @ceiroa. According to the documentation on [CustomLabel(s)](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_customlabels.htm), we should have one or the other. Since we are retrieving Custom Labels by name we should use `<name>CustomLabel</name>` and list each member individually as we were. According to the docs linked: "To retrieve specific labels by name, use CustomLabel and specify the label names as members." The example then sows this in action.

Secondly, regarding the Account and Contact listing in the manifest. The documentation states "Retrieving or deploying a standard object includes all custom and standard fields except for standard fields that aren’t customizable." The example listed on [this page](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm)  shows that is is normal to include the Standard Objects in the manifest as well.

CLosing this PR due to these findings.

**Comment by jlantz** [comment]
The source of truth for this should always be how Salesforce generates the package.xml when you retrieve the packaged metadata.  By that standard, both changes done by update_package_xml are correct changes and should be committed to the repo:

```
(venv) ~/dev/HEDAP (master) $ cumulusci2 task run retrieve_packaged --org feature
2016-12-02 10:29:51: Pending
2016-12-02 10:30:04: [Done]
2016-12-02 10:30:08: Extracted retrieved metadata into packaged

(venv) ~/dev/HEDAP (master) $ diff packaged/package.xml src/package.xml
358,361c358
<         <members>CustomLabels</members>
<         <name>CustomLabels</name>
<     </types>
<     <types>
---
>         <members>Account</members>
364a362
>         <members>Contact</members>
429c427
< </Package>
---
> </Package>
\ No newline at end of file

(venv) ~/dev/HEDAP (master) $ cumulusci2 task run update_package_xml
2016-12-02 10:31:27: Generating src/package.xml from metadata in src

(venv) ~/dev/HEDAP (master) $ git diff src/package.xml
diff --git a/src/package.xml b/src/package.xml
index 5a28e2c..b6dc2ee 100644
--- a/src/package.xml
+++ b/src/package.xml
@@ -355,11 +355,13 @@
         <name>CustomLabel</name>
     </types>
     <types>
-        <members>Account</members>
+        <members>CustomLabels</members>
+        <name>CustomLabels</name>
+    </types>
+    <types>
         <members>Address__c</members>
         <members>Affiliation__c</members>
         <members>Affl_Mappings__c</members>
-        <members>Contact</members>
         <members>Course_Enrollment__c</members>
         <members>Course_Offering__c</members>
         <members>Course__c</members>

(venv) ~/dev/HEDAP (master) $ diff packaged/package.xml
diff: missing operand after `packaged/package.xml'
diff: Try `diff --help' for more information.

(venv) ~/dev/HEDAP (master) $ diff packaged/package.xml src/package.xml 
429c429
< </Package>
---
> </Package>
\ No newline at end of file
```

**Comment by davidjray** [comment]
Thank you @jlantz.

**Comment by ceiroa** [comment]
Update package.xml format

**Pull request merged**
