### PR TITLE
Remove subclassed UpdateAdminProfile

### PR DESCRIPTION
**Pull request by jlantz**
Configure for CumulusCI's enhanced `update_admin_profile` task which avoids the need for subclassing to handle record type visibility and defaults

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by ceiroa** [comment]
Is this ready for review, @jlantz?

**Comment by jstvz** [comment]
LGTM

**Comment by annejackson** [comment]
Do you need me to test anything on this one @jlantz, @davidjray, @jstvz?

**Comment by jstvz** [comment]
@annejackson I don't think you need to do anything besides running the flow and verifying permissions.

**Comment by annejackson** [comment]
So would I do:
cci flow run dev_org
 and then:
cci flow run update_admin_profile

Or  just do soley- cci flow run update_admin_profile?
@jstvz  and @jlantz

**Comment by jstvz** [comment]
@annejackson `cci flow run dev_org` will include `update_admin_profile`, so that's all you need to do.

**Comment by annejackson** [comment]
This is all good. 
2018-10-10 11:26:38: [Success]: Succeeded
2018-10-10 11:26:38: Task complete: update_admin_profile
Merging PR. @jstvz  I will let you delete the branch. :)

**Comment by ceiroa** [comment]
I think this cause a build failure in master, @jstvz: https://mrbelvedereci.herokuapp.com/builds/38974

**Pull request merged**
