### PR TITLE
Fix the adv package check issue

### PR DESCRIPTION
**Pull request by weizsforg**
Update the Adv package check with the describe call. So, the code will work in both manage and unmanaged environment.
# Critical Changes

# Changes

# Issues Closed

# New Metadata
Hierarchy_Settings__c.Advancement_Namespace__c (Custom Field)
# Deleted Metadata

# Testing Notes
For this PR, we only need to do the regression test since there is no logic change in HEDA.

### CODE REVIEW

**Comment by weizsforg** [comment]
Hi @juliesnow, we add a field to store the Gift Processing Namespace in HEDA similar to NPSP. Can you review the description and help text. 

Description: The namespace of the Gift Processing package.
inlineHelpText: The namespace of the Gift Processing package.

Also, I added a Custom Label similar to NPSP to display an error when 1. Gift Processing is installed, but the customer does't have the license to use it. 2 Gift Processing is installed and licensed, but the config in custom metadata in Gift Processing is not set up correctly. For example, the typo in the API class API_HEDA -> API_HEDAA. I think we review it in NPSP branch already. 

giftProcessingConfigException
Gift Processing configuration error
Your org is missing required configuration for Gift Processing. Contact your admin for help.

**Comment by juliesnow** [comment]
Hi @weizsforg - going to mail you...

**Comment by annejackson** [comment]
@weizsforg am I regression testing HEDA or ADV? 
Should I test in a non namespaced scratch org and then also in a namespaced scratch org?

**Comment by weizsforg** [comment]
@annejackson We only need to do regression for HEDA test cases. I think the non namespaced scratch org should be ok. The main focus is to make sure HEDA works correctly as before.

**Comment by annejackson** [comment]
OK. It looks like this is ready for me to test. If that is correct, could you move the AA ticket @weizsforg? I will get to it after I do the GDPR testing.

**Comment by annejackson** [comment]
Also @weizsforg  do I need to make sure I can spin up a namespaced adv scratch org and a non-namespaced adv scratch org with this, or wait until it's merged into master or at another time?

**Comment by weizsforg** [comment]
@annejackson I don't think we need namespaced/non-namespaced adv scratch org for this. We can do it after we have a new HEDA package.

**Comment by annejackson** [comment]
This looks good. Was able to create a HEDA scratch org and did some spot check regression tests.

**Pull request merged**
