### PR TITLE
Feature/gender reciprocal settings

### LINKED ISSUE #404: Investigation: Allow HEDA Relationship Reciprocal Settings to use hed__Gender__c
Power of US Idea owner: [Tom Neuburger](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000006S8suAAC&tab=sfdc.ProfilePlatformOverview)
[Power of US Idea](https://powerofus.force.com/hub-ideas/1190)

Idea: Allow HEDA Relationship Reciprocal Settings to use hed__Gender__c

**Investigation is needed**
User is stating that even when a Gender is known that HEDA's Reciprocal Relationship Settings are overriding the Type value with the gender neutral value. Example provided by user: _This is particularly problematic when HEDA chooses "Siblings's Child" instead of Niece/ Nephew, or "Parent's Sibling" instead of Aunt/Uncle._ 

**Note:**
The steps below were captured by Jace in order to identify cause as well as to validate Idea request. There were a few things I came across that need to be investigated further to ensure accuracy in attempting to recreate issue identified by Tom vs. expected outcome of HEDA Reciprocal Settings.

**Create Relationship: Jane Doe (Aunt) to John Doe**

- Jane Doe does not have a salutation assigned on the Contact record
- Jane Doe is gender neutral on the Contact record
- Create a relationship between Jane Doe and John Doe (from John's Contact record) identifying Jane as the Aunt to John Doe
- From Jane Doe's Contact record the Related Contact for John Doe shows a Type value of “Sibling’s Child”
- From John Doe's Contact record the Related Contact for Jane Does shows a Type value of "Aunt"

 
**Create Relationship: Jimmy Doe (Uncle) to John Doe**

- Jimmy Doe does not have a salutation assigned on the Contact record
- Jimmy Doe is gender neutral on the Contact record
- Create a relationship between Jimmy Doe and John Doe (from John's Contact record) identifying Jimmy as the Uncle to John Doe
- From Jimmy Doe's Contact record the Related Contact for John Doe shows a Type value of "Sibling's Child"
- From John Doe's Contact record the Related Contact for Jimmy Doe shows a Type value of "Uncle"

 
**Assign a Gender value after Relationship has been created between 2 non-gender Contacts (INVESTIGATE)**

- Update the gender to “Female” for Jane Doe and refresh John Doe’s Contact record and the Type value of “Aunt” has been replaced with “Sibling’s Child”
- Update the gender to “Male” for Jimmy Doe and refresh John Doe's Contact record and the Type value of “Uncle” has been replaced with “Sibling’s Child”

 
**Create Relationship: Jenny Doe (Aunt) to John Doe (INVESTIGATE)**

- Jenny Doe was created with a salutation value of “Prof"
- Jenny Doe was assigned the value of “Female” for gender
- Create a relationship between Jenny Doe and John Doe (from John's Contact record) identifying Jenny as the Aunt to John Doe
- From John Doe's Contact record the Related Contact for Jenny Doe shows a Type value of "Aunt"
- Notice that because Gender was set before the relationship was established the Type value of "Aunt" stayed and did not update to "Sibling's Child" like it did for Jane Doe and Jimmy Doe.
- From Jenny Doe's Contact record the Related List for John Doe shows a Type value of “Sibling’s Child”

 
**Assign Gender value to John Doe (INVESTIGATE)**

When I set the Gender value of "Male" for John Doe's Contact record then the following occurs...

- John Doe's Type value changed from "Sibling's Child" to "Nephew" on both Jenny's and John's Contact Records.
- No change in Type value for the John Doe's relationships with Jane Doe and Jimmy Doe. Type values still show "Sibling's Child"

### PR DESCRIPTION
**Pull request by xinnanlisf**
# Critical Changes

# Changes
Fixed how gender is indicated in Contacts' relationships. If you update a Contact record to remove the value in HEDA's Gender field, we now change the Contact's relationship type from gender-specific to gender-neutral values. For example, if the Gender field for Jane Smith (female) is blank, we update the relationship with her nephew, John, from Aunt to Parent's Sibling. Previously, the relationship type remained Aunt.

# Issues Closed
Fixes #404

### CODE REVIEW

**Comment by xinnanlisf** [comment]
@lianeyee 

Could you please review the release notes? 

Thank you!

**Comment by lianeyee** [comment]
@xinnanlisf Does this capture the change? "When a Contact's gender is indicated in HEDA's Gender field, we now use gender-specific values (such as Aunt) to describe types of relationships between Contacts. Previously, we used gender-neutral values (such as Parent's Sibling) unless the value in the Contact's Salutation field was gender-specific.

**Comment by xinnanlisf** [comment]
@lianeyee 

Sorry, not entirely sure this is capturing the change. Previously if the gender value was none, the relationship type would not use any values.

For instance:

Jane, female
John, male
If we create a relationship on John's contact detail page that Jane is John's aunt, then Jane is John's Aunt and John is Jane's Nephew.
However, if we then change Jane's gender to none, on John's contact detail page, it still shows that Jane is John's Aunt instead of Parent's Sibling.
After the fix, on John's contact detail page, it shows that Jane is John's Parent's Sibling

I hope this makes sense to you. Feel free to let me know if you need further explanation or maybe a quick demo on this.

Thanks!

**Comment by lianeyee** [comment]
Ah, I see. There were a lot of scenarios described in the Hub thread and Jace's investigation, so I wasn't clear what we changed. Thanks for explaining the details. I'll reword and edit the description above.

**Comment by xinnanlisf** [comment]
@lianeyee 

Thanks, the release notes look awesome!:)

**Comment by xinnanlisf** [comment]
@davidjray 

I just tested in my environment. I totally agree what you found. Only one thing, in addition to sibling's parents, we might need to add parent's sibling to the default setting as well so that it can work in such scenario:

Timmy Smith(Male contact)
Joan Smith(Female contact)
Create relationship on Timmy Smith's detail page that Joan is Timmy's aunt
Change Joan's gender to none
The relationship on Timmy Smith's detail page should show that Joan is Timmy's parent's sibling instead of sibling's child

Let me know what you think and I will go ahead and make the changes.

Thanks again.
Xinnan

**Pull request merged**
