### PR TITLE
Fix 404 error for courses ApexDoc page. Added version number to home …

### LINKED ISSUE #470: 404 error loading the HEDA "Courses" ApexDoc page
Go to the HEDA ApexDocumentation page: http://developer.salesforce.org/HEDAP/ApexDocumentation/index.html 

Click the Courses link. The target page results in a file not found error: http://developer.salesforce.org/HEDAP/ApexDocumentation/Courses.html 

An attendee at last week's Higher Ed Sprint reported this error.

### LINKED ISSUE #482: Contact side menu for apexDoc page won't open
When clicking on contacts, it redirects the users to account.htm

### PR DESCRIPTION
**Pull request by xinnanlisf**
…page.

# Critical Changes

# Changes
On the [ApexDocumentation home page](http://developer.salesforce.org/HEDAP/ApexDocumentation/index.html), fixed the Courses link and added a version number.

# Issues Closed
Fixes #470 
Fixes #482

### CODE REVIEW

**Comment by ceiroa** [comment]
Hey @xinnanlisf, did you also verify the whole left menu works properly? I saw some issues last time I looked at it...

**Comment by xinnanlisf** [comment]
@ceiroa 

The side menu works fine after changing the group of ACCT_CannotDelete_TEST.

I added the version number to the homepage like NPSP as well. Will wait and see if Liane wants to add something else. Thank you!

**Comment by xinnanlisf** [comment]
@lianeyee 

Sorry I almost forgot. Could you take a look at the release note, please? Thank you!

**Comment by lianeyee** [comment]
@xinnanlisf Please see the suggested revision. I also added a link to the ApexDoc home page.

**Comment by lianeyee** [comment]
If you didn't end up adding the version number after all, obviously just delete that part. Thanks!

**Pull request merged**
