### PR TITLE
Implemented Spanish Translation

### LINKED ISSUE #492: Implement Spanish Translation
As a Spanish speaking HEDA user/customer/partner
I would like the new Spanish translations to be implemented
so that we can use HEDA specific items in Spanish

### PR DESCRIPTION
**Pull request by xinnanlisf**
# Critical Changes

# Changes
HEDA now provides a standard translation for Spanish. Some labels and custom labels, including some in HEDA Settings, that didn't make it into this round of translation will be translated in a future release.

# Issues Closed
Fixes #492
# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by xinnanlisf** [comment]
@lianeyee 

Good morning! Could you review the release note, please?

Thank you so much!

**Comment by lianeyee** [comment]
@xinnanlisf Thanks! I revised slightly to be consistent with how we describe the availability of translations in NPSP. See what you think.

**Comment by xinnanlisf** [comment]
Hi @weizsforg,

(Oops wrong pr)

Thank you for jumping on this pull request.

Basically, you need to switch the language to Spanish under your user settings and make sure all the translations are properly implemented.

You should be able to find the translation file under the work item.

Feel free to let me know if any questions!

**Comment by xinnanlisf** [comment]
@davidjray 

Hi David, could you do a quick check before we assign this to QA?

Thank you!

**Comment by xinnanlisf** [comment]
@davidjray 

Great catch! I just removed all the English translation files.

**Comment by davidjray** [comment]
@chrismcmahon this is ready for QA!

**Comment by xinnanlisf** [comment]
Added those English translation files back to support build script.

**Pull request merged**
