### PR TITLE
Disabling tests if advancement installed.

### PR DESCRIPTION
**Pull request by ceiroa**
# Critical Changes

# Changes
- Disabling tests inside TDTM_DMLgt200_TEST if the gift entry app is also installed (they were causing CPU timeout issues).

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by xinnanlisf** [comment]
@ceiroa 

Looks good to me. Approved!

**Comment by annejackson** [comment]
What should I focus on in testing this @ceiroa  and @xinnanlisf ?

**Comment by xinnanlisf** [comment]
Hey @annejackson there is really nothing to test for this PR. I just assigned it to you for best practice of our process. Feel free to merge it but let me know if any concern.

**Comment by annejackson** [comment]
Thanks @xinnanlisf - I just spun up a scratch up to the branch and navigated through heda/heda settings. Merging this PR.

**Pull request merged**
