### PR TITLE
REL_Relationships_TDTM gives Entity is Deleted error

### LINKED ISSUE #510: REL_Relationships_TDTM gives Entity is Deleted error
When trying to delete all relationships for a Contact in a single operation, the REL_Relationships_TDTM trigger deletes the reciprocal relationships in the middle of the delete. This causes an Entity is Deleted error when the delete attempts to complete.

I've updated the trigger to keep track of what relationships have been deleted and submitted a pull request.

### PR DESCRIPTION
**Pull request by weizsforg**
Merging pull request from community #522 

# Critical Changes

# Changes
- Fixed an error that prevented you from deleting a relationship and its corresponding reciprocal relationship in a single operation. Thank you @kyleschmid for your contribution! 

# Issues Closed
Fixes #510 

# New Metadata

# Deleted Metadata

# Testing Notes
Steps to reproduce:
1. Create two Contacts.
2. Create a relationship from one Contact (system should create a reciprocal relationship for another Contact)
3. Delete the relationship and the reciprocal relationship in the same operation. System will show the "Entity is Deleted" exception.
Example Code to run the developer console:
```
Contact c1 = new Contact(LastName = 'test1');
Contact c2 = new Contact(LastName = 'test2');
insert new List<Contact>{c1, c2};

insert new Relationship__c(Contact__c = c1.Id, RelatedContact__c = c2.Id);
delete [SELECT Id FROM Relationship__c WHERE Contact__c = :c1.Id OR Contact__c = :c2.Id];
```

How to verify this PR:
System should be able to delete the relationship and its corresponding reciprocal relationship in a single operation without error.

### CODE REVIEW

**Comment by weizsforg** [comment]
Hi @xinnanlisf , can you please have a look about this PR?

**Comment by weizsforg** [comment]
Hi @lianeyee , can you please review the Changes in this PR?

**Comment by lianeyee** [comment]
@weizsforg Reviewed and edited. Like the other PR, I also formatted as a bullet. I believe that's our standard for release notes. Thanks!

**Comment by weizsforg** [comment]
@lianeyee Thanks! Looks great.

**Pull request merged**
