### PR TITLE
Fixed bug: primary contact changed if a new contact connected to this…

### LINKED ISSUE #562: Primary Contact: moving a primary contact from one household to another household makes that contact the primary account of the household it was moved too
This should not happen.  

My default account model was Household and I had automatic household naming on.

Steps to duplicate:
1. Create a contact. It will automatically be the primary contact for this household. 
2. (not sure this step is necessary) Un-associate the contact as the primary contact (make it blank) for that household. Then re-associate the contact as the primary contact.
3. Go back to Contacts and create a brand new contact to be auto-assigned a new household account. This contact will be the primary contact for this household.
4. Move the contact created in step 1/2 to the household created in step 3 . 
Expected:
The moved contact should NOT be listed as the primary contact to the moved account/household from step 3. It should also still be listed as the primary contact for the old/blank/anonymous household.

Actual: 
The moved contact WAS listed as the primary contact to the moved account/household from step 3 (incorrect). It was listed as the primary contact for the old/blank/anonymous household. (correct)

### PR DESCRIPTION
**Pull request by xinnanlisf**
# Critical Changes

# Changes
- Primary Contact on a Household Account does not change when a user adds a new Contact to the Household. If you want to change Primary Contact, simply update the field to the Contact you want.

# Issues Closed
Fixes #562

# New Metadata

# Deleted Metadata

# Testing Notes
1. Create a contact. It will automatically be the primary contact for this household. 
2. (not sure this step is necessary) Un-associate the contact as the primary contact (make it blank) for that household. Then re-associate the contact as the primary contact. 
3. Go back to Contacts and create a brand new contact to be auto-assigned a new household account. This contact will be the primary contact for this household. 
4. Move the contact created in step 1/2 to the household created in step 3 .

### CODE REVIEW

**Comment by xinnanlisf** [comment]
Hey @sam-knox,

Could you review the release notes please? Thank you! :)

**Comment by sam-knox** [comment]
Release note reviewed and updated.

**Comment by annejackson** [comment]
@xinnanlisf  does anything need to be done for this showing:
This branch is out-of-date with the base branch
Merge the latest changes from master into this branch. (with update branch available?)

**Comment by annejackson** [comment]
All tests have passed. Now moving a contact to another household does not replace the primary contact field with that newest added contact. The Primary contact field stays the original/1st added contact for the household. Merging PR.  @xinnanlisf

**Pull request merged**
