### PR TITLE
Feature/lparrott/gdpr email log

### LINKED ISSUE #567: GDPR: Emailing error log should be disabled by default
In order to comply with GDPR, the checkbox under HEDA settings for emailing the contents of the asynchronous jobs error log should be disabled by default.

We do not need to worry about existing orgs, and they can disable it themselves.

### PR DESCRIPTION
**Pull request by lparrott**
# Critical Changes

# Changes

- To help you comply with various data protection and privacy regulations, the Send Error Notifications setting in HEDA Settings is now disabled by default.

# Issues Closed

Fixes #567 

# New Metadata

# Deleted Metadata

# Testing Notes

Steps to reproduce #567 :

1. Install the HEDA package to a new org with this change included.
2. From the HEDA App, navigate to the HEDA Settings tab, then to the "System" sub tab of that page.
3. The “Send Error Notifications” should be unchecked.

### CODE REVIEW

**Comment by weizsforg** [comment]
Hi @lparrott , usually we will ask @lianeyee to review the notes after we create the PR.

**Comment by lianeyee** [comment]
Thanks @weizsforg and @lparrott. Great draft. I edited slightly. Remember to format these items as bullets.

I'd like @sam-knox to take a look, since he's heading up the GDPR work from the Doc side. Not sure if we want to lead with "To comply with" or "To prepare for compliance with" or something else?

**Comment by sam-knox** [comment]
Do we even need to specifically call out GDPR at all? That might have been the reason why this change was made but we need to be careful about saying anything in particular will make you compliant. A big part of the onus is actually on the customer.  Look at the tone of what core has published about data privacy compliance: https://help.salesforce.com/articleView?id=data_protection_and_privacy.htm&type=5

So maybe something more like "To help you comply with various data protection and privacy regulations, the Send Error Notifications setting in HEDA Settings is now disabled by default."

I'm learning as quick as I can about all this, but that's my current read of the situation.

**Comment by lianeyee** [comment]
@sam-knox That makes sense and sounds great to me. @juliesnow Do you have access to the adv repo yet? If so, would you like to make that final update to the release notes? If not, let me know.

**Comment by juliesnow** [comment]
Dylan said he gave me access, but I still don't see it in my list of repos. Will look into it and get back to you...

**Comment by weizsforg** [comment]
@lparrott Great work!

**Comment by lparrott** [comment]
Hi @annejackson, this PR is ready for your review.

**Comment by annejackson** [comment]
@lparrott  and @weizsforg 
This change just looks like I am making sure that when I spin up a scratch org this checkbox is disabled by default, right? Question- A user could choose to enable/check the checkbox themselves, correct? 

error notifications

**Comment by lparrott** [comment]
@annejackson Yep, that checkbox should be unchecked in new scratch orgs that include this code change. After installing the package, they are free to change the setting.

**Comment by annejackson** [comment]
This looks good @lparrott - the checkbox was unchecked in new scratch org for this code change. The user also had control of being able to check or uncheck the box going forward. I'll check this in the QA sandbox when it gets updated with this release. After installing the package, they are free to change the setting. Merging this pull request.

**Pull request merged**
