### PR TITLE
Avoid sending email in the unit test

### LINKED ISSUE #490: Avoid attempting email sends in unit tests

### PR DESCRIPTION
**Pull request by weizsforg**
Updated the code to prevent sending email when running the apex unit test.

# Critical Changes

# Changes
Suppress email notifications for Apex unit tests.
# Issues Closed
Fixes #490 
# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by weizsforg** [comment]
Hi @lianeyee , this pull request is about update the code to not sending email in the Apex unit test cases. I don't think user need to do anything about it. So, I just left Critical Changes and Changes part empty. Can you please do a review for it?

**Comment by lianeyee** [comment]
Thanks for the ping, @weizsforg. Since I see this item in Changes now, did you decide to mention it, after all? That's fine (I edited it slightly). It's also fine to omit, as long as the Issue Description provides the same info. Your call whether to keep in Changes or leave out.

**Comment by weizsforg** [comment]
Thanks for your help @lianeyee . I think we can keep in Changes.

**Comment by xinnanlisf** [comment]
@davidjray @chrismcmahon 

This is the pr we discussed in the meeting. Sorry about the confusion I gave. I was thinking about the other work item. 

Feel free to let me or @weizsforg know if any questions or concerns.

**Comment by xinnanlisf** [comment]
Hi @weizsforg,

Thank you for jumping on this pull request.

Basically, you need to switch your language to Spanish under your user settings and make sure all the translations are correctly implemented.

The translation file is under the work item.

Feel free to let me know if any questions!

**Pull request merged**
