### PR TITLE
Fixing reparenting affiliation creating duplicate affiliation

### PR DESCRIPTION
**Pull request by xinnanlisf**
# Critical Changes

# Changes
We've fixed a bug that created duplicate Affiliations when users reparented an existing Primary Affiliation with a different Contact/Account.

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes
1. Deploy HEDA to a scratch org
2. Create a non-admin account(business org etc)
3. Create two contacts
4. Set the primary field(primary business org for instance) as contact#1
5. Go to contact#1 and find the new affiliation(affiliation#1) under related list(affiliation account)
6. Go to affiliation record page and update the parent contact to contact#2
7. Make sure no new affiliation is created, affiliation#1 is under contact#2 and is primary.

### CODE REVIEW

**Comment by xinnanlisf** [comment]
@juliesnow could you review the release note of this PR please? Thank you!

**Comment by annejackson** [comment]
Testing in progress. Also pinged @jacebryan  and @aligeez to check out the changes section for release notes.

**Comment by annejackson** [comment]
This looks good. Will merge once we get the final okay on the suggested changes from @juliesnow.

**Comment by juliesnow** [comment]
@xinnanlisf + @annejackson - Looks good!

**Comment by annejackson** [comment]
Merging pull request. All looks good.

**Comment by xinnanlisf** [comment]
@juliesnow added the bullet point to the release note. Fyi. :)

**Comment by aligeez** [comment]
For Release Notes description: 

We've fixed a bug that created duplicate Affiliations when users re-parented an existing Primary Affiliation with a different Contact/Account. With this fix, when you re-parent an existing Primary affiliation with a new or different Contact (Account), it will keep the primary affiliation as the sole affiliation without creating any other ones. This does not apply to regular affiliations, just "primary". 

@xinnanlisf  - thanks for your help :)

**Comment by juliesnow** [comment]
@aligeez - Have provided proposed rewrite in WI. Pls lmk if you have ?s/suggestions. thx!

**Pull request merged**
