### PR TITLE
Remove error tab

### PR DESCRIPTION
**Pull request by xinnanlisf**
# Critical Changes

# Changes
Remove error tab to avoid exception when upgrading HEDA.
# Issues Closed

# New Metadata

# Deleted Metadata
Error.tab
# Testing Notes

### CODE REVIEW

**Comment by annejackson** [comment]
Kevin's note to the Power of Us Hub:
During this week’s HEDA push upgrade to sandboxes (version 1.56), we noticed a number of sandboxes where the installation failed. This can sometimes happen for a number of reasons, but this time we noticed that the failure was tied directly to an item in our release. Version 1.56 included some enhancements giving administrators to control the number of records in HEDA’s Error object. In doing so, we also included a Tab for the Errors object to make it easier for Administrators to review those records.
That works fine for most orgs…but if a system administrator already created a custom object tab for the Error object, that directly conflicts with the new tab in the HEDA release, and causes the update to fail.
So if this is affecting one of your orgs, you have a couple of options:
1. Let it ride…version 1.56 is pretty small so it won’t affect your org to just wait until 1.57 comes through (keep in mind we’ll skip the next release cycle to let you absorb the Summer 18 upgrade)
2. Delete your custom Errors tab so it doesn’t conflict with the one included in the upgrade
a. If you do this in sandbox, you can manually install the 1.56 upgrade from GitHub (1.56 install link available at https://github.com/).
b. If you do this in production before the HEDA push on 5/29, 1.56 should upgrade just fine
If you delete the tab and the upgrade still fails, check in here on the Hub or open a case to determine is something else is preventing the install.

**Comment by ceiroa** [comment]
Xinnan’s idea sounds good. After we cut 1.56, for regression we could
install heda 1.54 manually from the link in a dev org and then install
1.56.

-Carlos

On May 25, 2018, at 3:27 PM, Anne Jackson <notifications@github.com> wrote:

Kevin's note to the Power of Us Hub:
During this week’s HEDA push upgrade to sandboxes (version 1.56), we
noticed a number of sandboxes where the installation failed. This can
sometimes happen for a number of reasons, but this time we noticed that the
failure was tied directly to an item in our release. Version 1.56 included
some enhancements giving administrators to control the number of records in
HEDA’s Error object. In doing so, we also included a Tab for the Errors
object to make it easier for Administrators to review those records.
That works fine for most orgs…but if a system administrator already created
a custom object tab for the Error object, that directly conflicts with the
new tab in the HEDA release, and causes the update to fail.
So if this is affecting one of your orgs, you have a couple of options:

   1. Let it ride…version 1.56 is pretty small so it won’t affect your org
   to just wait until 1.57 comes through (keep in mind we’ll skip the next
   release cycle to let you absorb the Summer 18 upgrade)
   2. Delete your custom Errors tab so it doesn’t conflict with the one
   included in the upgrade
   a. If you do this in sandbox, you can manually install the 1.56 upgrade
   from GitHub (1.56 install link available at https://github.com/).
   b. If you do this in production before the HEDA push on 5/29, 1.56
   should upgrade just fine
   If you delete the tab and the upgrade still fails, check in here on the
   Hub or open a case to determine is something else is preventing the install.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SalesforceFoundation/HEDAP/pull/607#issuecomment-392172171>,
or mute the thread

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXWbKAAX" target="_blank">W-025067</a>

**Comment by xinnanlisf** [comment]
@weizsforg  this is the PR we talked about during standup. Thank you!

**Comment by weizsforg** [comment]
Hi @xinnanlisf , I think the code looks good. We just need to test 1. If the tab is removed from the package when we cut the release. 2. If we can upgrade an org from the the version that has the Error Tab in their org.

**Comment by xinnanlisf** [comment]
@annejackson fyi, what @weizsforg said

**Comment by annejackson** [comment]
@xinnanlisf, so far with testing #1 above I saw this:
In my new scratch org off this PR, this is what I saw:
-errors tab was not automatically there/added in HEDA app
-When trying to edit a profile in setup-> I could see Errors custom tab as tab hidden by default
-In setup and tabs-> I could see Errors in custom tabs list
-In setup->app manager-> errors listed as available tabs but not in selected tabs in heda app

I do have some sandboxes setup already to get the 1.57 release once we cut it. 

For testing this PR/change, is there a way to spin up a scratch or dev org->then install heda 1.55 manually from the link in a dev org and then put this fix/update on it? Is that what you were thinking when you mentioned this: 
It might be good to test this somehow in an org that already has the Errors tab and make sure things are fine. Some notes per Xinnan- maybe we can try to create a dummy managed package and install it in a dev org, add an error tab and upgrade the managed package.

**Comment by xinnanlisf** [comment]
Hey @juliesnow @aligeez, do you feel we need a release note for this PR?

**Comment by annejackson** [comment]
Metadata is now removed for the errors tab. I could manually add the errors tab fine as well. Scheduled job still worked. I have some data setup in sandboxes with different scenarios (on version 1.55 where errors tab had already been added and version 1.56 failed to install, and I also have my successful sandbox where 1.56 did get installed). More testing will be done on sandboxes. Merging this PR.

**Pull request merged**
