### PR TITLE
Clarify Backfill instruction text

### PR DESCRIPTION
**Pull request by davidjray**
# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Comment by davidjray** [comment]
@chrismcmahon Do you mind reviewing the changes I made to the text based on your feedback?

**Comment by chrismcmahon** [comment]
looks much better to me, I like it

**Comment by davidjray** [comment]
@chrismcmahon glad this is better. Once Liane has a chance to review then we can merge. Thanks!

**Comment by davidjray** [comment]
@chrismcmahon Liane was able to review the changes, and I applied them. If all looks good, do you mind merging?

**Pull request merged**
