### PR TITLE
Fixing namespace error on HEDA Settings page when NPSP and HEDA are i…

### LINKED ISSUE #581: HEDA Settings Error when installed with NPSP
Receiving an error in the page when NPSP and HEDA managed packages are installed together. The content doesn't load at all. Error: An internal server error has occurred Error ID: 346429827-100730 (319857279)

### PR DESCRIPTION
**Pull request by lparrott**
…nstalled in the same org

The issue here was that a query to get the "hed" namespace was using a class name that is also in NPSP, meaning sometimes it returned "npsp", causing the error.

# Critical Changes

# Changes

- In the rare case that NPSP and HEDA are installed in the same org, the HEDA Settings page no longer loads with an error.

# Issues Closed

Fixes #581 

# New Metadata

# Deleted Metadata

# Testing Notes

This one is tricky to test:

1. Setup an org with the managed package version of NPSP, 
2. Next, install the HEDA managed package, including this change, to ensure that both namespaces are being used.
2. Navigate to the HEDA app, then HEDA Settings page.
3. The page should load correctly, with no "internal server error" message.

### CODE REVIEW

**Comment by lianeyee** [comment]
@juliesnow This is headed to QA so could you give the release note a review? Looks pretty good. I'd suggest mentioning that this was causing an error in HEDA Settings.

**Comment by juliesnow** [comment]
thx!

**Comment by juliesnow** [comment]
@lparrott, @annejackson, and @lianeyee Please check out the updated comment and suggest any changes. Thanks!

**Comment by annejackson** [comment]
Should we be concerned about the Namespace test failures @lparrott  and @ceiroa?

**Comment by ceiroa** [comment]
I don't think we need to be concerned about that one. Could you please confirm, @cpolcyn?

**Comment by cpolcyn** [comment]
For now the namespaced tests are not required to merge, but you may want to look into it anyway.

**Comment by annejackson** [comment]
My tests have passed (and I tested in both a regular scratch org and a namespaced scratch org). Heda settings page is displaying for both now! @lparrott

**Comment by annejackson** [comment]
All checks/tests have passed in metaci now-Per Luke-The namespace re-test passed! Merging this PR.

**Pull request merged**
