### PR TITLE
Enable French for HEDA

### PR DESCRIPTION
**Pull request by xinnanlisf**
# Critical Changes

# Changes
- We're excited to announce that French is now a fully supported language in HEDA. To verify that French is enabled in your org, from Setup, go to Language Settings, and verify that French is listed in the "Displayed Languages" list. You can then change the language for your org or have users change their personal language settings.

# Issues Closed

# New Metadata
Account-fr.objectTranslation
Address__c-fr.objectTranslation
Affiliation__c-fr.objectTranslation
Affl_Mappings__c-fr.objectTranslation
Contact-fr.objectTranslation
Course_Enrollment__c-fr.objectTranslation
Course_Offering__c-fr.objectTranslation
Course__c-fr.objectTranslation
Error__c-fr.objectTranslation
Hierarchy_Settings__c-fr.objectTranslation
Program_Enrollment__c-fr.objectTranslation
Relationship_Auto_Create__c-fr.objectTranslation
Relationship_Lookup__c-fr.objectTranslation
Relationship__c-fr.objectTranslation
Term__c-fr.objectTranslation
Trigger_Handler__c-fr.objectTranslation
fr..translation

# Deleted Metadata

# Testing Notes

To change your language preference in a Salesforce org:
1. In Lightning, click your profile image in the top-right, then "Settings"
2. Select Language & Time Zone in the left menu
3. Update language to "francais"

### CODE REVIEW

**Comment by lparrott** [comment]
@xinnanlisf Sounds like we need to add New Metadata and Testing Notes to this PR description.
@lianeyee Will also want to review the notes.
Lastly, @annejackson can test this when she's ready.

**Comment by lianeyee** [comment]
Actually, @lparrott, could you make Julie the reviewer for release notes instead of me?

**Comment by juliesnow** [comment]
@xinnanlisf @lparrott Hi both. Can you please provide us with the steps users need to complete to enable French in HEDA? French is already included in the list of Displayed languages (in Setup|Language Settings). Do they need to import .stf files in Translation Workbench, or...?

**Comment by lparrott** [comment]
@juliesnow Once the language files are deployed to an org, a User just needs to update their Language preference under personal settings. I've updated the Testing Notes with these steps.

**Comment by juliesnow** [comment]
Okay, so we have two questions:
1) So, since French is listed as a Displayed Language, the files are already available and no further action is needed, yes? They only need to set their personal preferences. 
2) Are we only letting them specify language settings at the user level, or should we tell an admin how to specify a language setting for their org? If org-level, too, pls provide similar details. Thanks!

**Comment by xinnanlisf** [comment]
@juliesnow 

1. Yes users do not need to import any file.
2. I think admins can configure default language in Setup->company information. It really depends on their need of languages. @lparrott correct me if I am wrong.

**Comment by annejackson** [comment]
Testing is complete. Did the following:
Tested with language set to English, did high level feature checks. Saw English.
Tested with language set to French, did high level feature checks. Saw French.
Merging this PR @xinnanlisf

**Pull request merged**
